export * from './setupRouter'
export * from './setupAsset'
export * from './setupDirective'
export * from './setupNprogress'
export * from './setupComponent'
export * from './setupStore'
export * from './setupI18n'
export * from './BroadcastChannel'